version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:14-alpine
    container_name: zephyrpay-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zephyrpay
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis service for caching
  redis:
    image: redis:7-alpine
    container_name: zephyrpay-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: zephyrpay-backend
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      - POSTGRES_SERVER=postgres
      - REDIS_HOST=redis
      - DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
